site: Sidey
url: #yoururl
title: Sidey
description: Simple and minimalistic jekyll blogging theme.
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

# The full URL to your site. Note: site.github.url will be used by default.
url: duddits45.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/sidey"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
